apiVersion: v1
kind: Namespace
metadata:
  name: opensearch
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opensearch-master
  namespace: opensearch
spec:
  podManagementPolicy: Parallel
  serviceName: opensearch-master-headless
  replicas: 3
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - opensearch
              topologyKey: kubernetes.io/hostname
            weight: 1
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: opensearch
        image: opensearchproject/opensearch:latest
        resources:
            requests:
              cpu: "1"
              memory: "200Mi"
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 9200
          timeoutSeconds: 3
        startupProbe:
          failureThreshold: 30
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 9200
          timeoutSeconds: 3
        securityContext:
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1000
        volumeMounts:
        - name: opensearch-data
          mountPath: /usr/share/opensearch/data
        env:
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: cluster.initial_master_nodes
            value: "opensearch-master-0,opensearch-master-1,opensearch-master-2"
          - name: discovery.seed_hosts
            value: opensearch-master-headless
          - name: cluster.name
            value: opensearch-cluster
          - name: network.host
            value: 0.0.0.0
          - name: OPENSEARCH_JAVA_OPTS
            value: "-Xms512M -Xmx512M"
          - name: node.roles
            value: master,ingest,data,remote_cluster_client,            
      initContainers:
      - name: fsgroup-volume
        image: busybox:latest
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/opensearch/data"]
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: opensearch-data
          mountPath: /usr/share/opensearch/data
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      volumes:
      - name: opensearch-data
        emptyDir: {}
---
kind: Service
apiVersion: v1
metadata:
  name: opensearch
  namespace: opensearch
  labels:
    app: opensearch
spec:
  selector:
    app: opensearch
  type: ClusterIP
  ports:
    - port: 9200
      name: http
    - port: 9300
      name: transport
---
kind: Service
apiVersion: v1
metadata:
  name: opensearch-master-headless
  namespace: opensearch
  labels:
    app: opensearch
spec:
  selector:
    app: opensearch
  type: ClusterIP
  ports:
    - port: 9200
      name: http
    - port: 9300
      name: transport
  clusterIPs: None
