apiVersion: v1
kind: Namespace
metadata:
  name: opensearch
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opensearch-master
  namespace: opensearch
spec:
  serviceName: opensearch
  replicas: 3
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - opensearch
              topologyKey: kubernetes.io/hostname
            weight: 1
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: opensearch
        image: opensearchproject/opensearch:latest
        resources:
            limits:
              cpu: "2"
              memory: "1000Mi"
            requests:
              cpu: "1"
              memory: "500Mi"
        ports:
        - containerPort: 9200
          name: rest-api
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: opensearch-data
          mountPath: /usr/share/opensearch/data
        env:
          - name: cluster.name
            value: opensearch-cluster
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: discovery.seed_hosts
            value: "opensearch-master-0.opensearch,opensearch-master-1.opensearch,opensearch-master-2.opensearch"
          - name: cluster.initial_master_nodes
            value: "opensearch-master-0,opensearch-master-1,opensearch-master-2"
          - name: OPENSEARCH_JAVA_OPTS
            value: "-Xms512M -Xmx512M"
      initContainers:
      - name: fix-permissions
        image: busybox:latest
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/opensearch/data"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: opensearch-data
          mountPath: /usr/share/opensearch/data
      - name: increase-vm-max-map
        image: busybox:latest
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: set-ulimit
        image: busybox:latest
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true
      volumes:
      - name: opensearch-data
        emptyDir: {}
---
kind: Service
apiVersion: v1
metadata:
  name: opensearch
  namespace: opensearch
  labels:
    app: opensearch
spec:
  selector:
    app: opensearch
  type: ClusterIP
  ports:
    - port: 9200
      name: rest-api
    - port: 9300
      name: transport
